/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\public\models\spaceDebris\blackHole.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/blackHole.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Icosphere.geometry} material={materials['Material.002']} />
      <mesh geometry={nodes.Cube.geometry} material={materials['Material.003']} scale={[3.873, 0.076, 3.873]} />
    </group>
  )
}

useGLTF.preload('/blackHole.glb')
