/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\public\models\spaceDebris\Moon.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Moon.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Moon.geometry} material={materials.Mat} />
    </group>
  )
}

useGLTF.preload('/Moon.glb')
