/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\public\models\spaceDebris\Planet.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Planet.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Planet_7.geometry} material={materials.Atlas} scale={100} />
    </group>
  )
}

useGLTF.preload('/Planet.glb')
