/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\public\models\airplane\SpaceStation.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/SpaceStation.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.InternationalSpaceStation_mesh.geometry} material={materials.InternationalSpaceStation_mat} />
    </group>
  )
}

useGLTF.preload('/SpaceStation.glb')
